author: stsinghua

keywords: Hexo, Theme-AD

description: stsinghua

# 导航栏头部名称
nav_name: stsinghua

# 导航栏座右铭
motto: "never give up"

github: "https://github.com/stsinghua/"

# 站点图标和APP图标
favicon:
  icon: /favicon/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss:

# 自定义样式文件
custom_styles:

# 自定义脚本文件
custom_scripts:

# 代码高亮主题: normal | night | night blue | night bright | night eighties | night gray
highlight_theme: "night gray"

# 开启数学公式渲染
mathjax: true

copyright:
  enable: true
  author: "stsinghua"
  show_link: true
  more: '版权声明: 本博客所有文章除特别声明外, 均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 许可协议. 转载请注明出处!'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2017-01-01"

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: Hyq9wkH495DgNHWhDQCOfQSp  # 填写您的appid
  appkey: WaR7nrzhliHj9aVwdQzkdlGd  # 填写您的appkey
  comment: false # 是否开启评论系统
  count: false # 是否开启文章统计

# 需要保证leancloud.count为true
welcome:
  enable: false
  interval: 30

# 需要保证leancloud.comment为false
disqus:
  enable: false
  id:

# 需要保证leancloud.count为false
busuanzi: false

# 需要保证lock
lock: true

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
passwords:
  - 515e6c90e4b0d45fdd94f6e9ecfe5e2888d409326974945e6aa941afa9c9ed0d  # stsinghua

share:
  twitter: false
  facebook: false
  weibo: false
  qq: true
  wechat: true

analytics:
  baidu:
    enable: false
  google:
    enable: false
    id:
  "360":
    enable: false
    id:

# 打赏图片
reward:
  -
    src: /images/wechat.png
    alt: "WeChat"
  -
    src: /images/alipay.png
    alt: "AliPay"

# 第三方库的CDN地址
# 请根据情况自行决定是否替换为国内CDN
cdn:
  leancloud: "//cdn.jsdelivr.net/npm/leancloud-storage@3.11.1/dist/av-min.js"
  mathjax: "//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
  valine: "//unpkg.com/valine/dist/Valine.min.js"
  busuanzi: "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"
  font_awesome: "//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"

nav:
  -
    name: "首页"
    path: "/"
  -
    name: "归档"
    path: "/archives/"
  -
    name: "标签"
    path: "/tags/"
  -
    name: "分类"
    path: "/categories/"
  -
    name: "友链"
    path: "/friends/"
  -
    name: "关于"
    path: "/about/"

footer:
  -
    title: "博客推荐"
    children:
      -
        name: "廖雪峰的官方网站"
        path: "https://www.liaoxuefeng.com/"
      -
        name: "阮一峰的个人网站"
        path: "http://ruanyifeng.com/"
  -
    title: "网站推荐"
    children:
      -
        name: "菜鸟教程"
        path: "http://www.runoob.com/"
      -
        name: "MND WEB 文档"
        path: "https://developer.mozilla.org/zh-CN/"
  -
    title: "论坛推荐"
    children:
      -
        name: "Java World"
        path: "https://www.javaworld.com/"
      -
        name: "Stackoverflow"
        path: "https://stackoverflow.com/"
      #-
      #  title: "常逛网站"
      #  children:
      #    -
      #      name: "Dzone"
      #      path: "https://dzone.com/"
      #    -
      #      name: "Java Study"
      #      path: "http://how2j.cn/"
footer_contact: "邮箱: stsinghua@gmail.com"

# 如果您的友链头像都保存在其他服务器上，可以通过更改friends_avatar_cdn字段来配置前缀地址，例如：friends_avatar_cdn: "https://godbmw.com/blog-static"
friends:
  -
    nickname: tools # 友链名称
    avatar: /images/friends/pangxie.png # 友链头像
    site: https://tool.lu/ # 友链地址
    meta: 在线工具 # 友链介绍
    show: true # 是否展示此友链
  -
    nickname: tensorflow-news # 友链名称
    avatar: /images/friends/maotouying.png # 友链头像
    site: http://tensorflownews.com # 友链地址
    meta: TensorFlow教程、资源，AI交流社区 # 友链介绍
    show: true # 是否展示此友链
  -
    nickname: java-design-patterns # 友链名称
    avatar: /images/friends/zhangyu.png # 友链头像
    site: https://github.com/iluwatar/java-design-patterns?utm_source=gold_browser_extension # 友链地址
    meta: 设计模式大全(java版) # 友链介绍
    show: true # 是否展示此友链

